//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFEX.plantilla.api.ESB_AFEX_LDAP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AplicacionAuth", Namespace="http://tempuri.org/")]
    public enum AplicacionAuth : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AfexWeb = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoneyGram = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AfexChangeMESA = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Afexpress = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CumplimientoWEB = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eafex = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFEXpressWEB = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Facturador = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MantenedoresGiros = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFEXchangeGIROS = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CartolaIntegral = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFEXPal = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GestionInformatica = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioAplicacion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UsuarioAplicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidacionAuth", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ValidacionAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsAuthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsAuth {
            get {
                return this.IsAuthField;
            }
            set {
                if ((this.IsAuthField.Equals(value) != true)) {
                    this.IsAuthField = value;
                    this.RaisePropertyChanged("IsAuth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap")]
    public interface IESB_AV_ServicioAuthSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutenticarLDAP", ReplyAction="*")]
        AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPResponse AutenticarLDAP(AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutenticarLDAP", ReplyAction="*")]
        System.Threading.Tasks.Task<AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPResponse> AutenticarLDAPAsync(AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarFirma", ReplyAction="*")]
        AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaResponse ValidarFirma(AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarFirma", ReplyAction="*")]
        System.Threading.Tasks.Task<AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaResponse> ValidarFirmaAsync(AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarLDAPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarLDAP", Namespace="http://tempuri.org/", Order=0)]
        public AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequestBody Body;
        
        public AutenticarLDAPRequest() {
        }
        
        public AutenticarLDAPRequest(AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutenticarLDAPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public AFEX.plantilla.api.ESB_AFEX_LDAP.AplicacionAuth aplicacion;
        
        public AutenticarLDAPRequestBody() {
        }
        
        public AutenticarLDAPRequestBody(string usuario, string password, AFEX.plantilla.api.ESB_AFEX_LDAP.AplicacionAuth aplicacion) {
            this.usuario = usuario;
            this.password = password;
            this.aplicacion = aplicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarLDAPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarLDAPResponse", Namespace="http://tempuri.org/", Order=0)]
        public AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPResponseBody Body;
        
        public AutenticarLDAPResponse() {
        }
        
        public AutenticarLDAPResponse(AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutenticarLDAPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AFEX.plantilla.api.ESB_AFEX_LDAP.UsuarioAplicacion[] AutenticarLDAPResult;
        
        public AutenticarLDAPResponseBody() {
        }
        
        public AutenticarLDAPResponseBody(AFEX.plantilla.api.ESB_AFEX_LDAP.UsuarioAplicacion[] AutenticarLDAPResult) {
            this.AutenticarLDAPResult = AutenticarLDAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarFirmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarFirma", Namespace="http://tempuri.org/", Order=0)]
        public AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequestBody Body;
        
        public ValidarFirmaRequest() {
        }
        
        public ValidarFirmaRequest(AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarFirmaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firma;
        
        public ValidarFirmaRequestBody() {
        }
        
        public ValidarFirmaRequestBody(string usuario, string firma) {
            this.usuario = usuario;
            this.firma = firma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarFirmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarFirmaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaResponseBody Body;
        
        public ValidarFirmaResponse() {
        }
        
        public ValidarFirmaResponse(AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarFirmaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AFEX.plantilla.api.ESB_AFEX_LDAP.ValidacionAuth ValidarFirmaResult;
        
        public ValidarFirmaResponseBody() {
        }
        
        public ValidarFirmaResponseBody(AFEX.plantilla.api.ESB_AFEX_LDAP.ValidacionAuth ValidarFirmaResult) {
            this.ValidarFirmaResult = ValidarFirmaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IESB_AV_ServicioAuthSoapChannel : AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ESB_AV_ServicioAuthSoapClient : System.ServiceModel.ClientBase<AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap>, AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap {
        
        public ESB_AV_ServicioAuthSoapClient() {
        }
        
        public ESB_AV_ServicioAuthSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ESB_AV_ServicioAuthSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESB_AV_ServicioAuthSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESB_AV_ServicioAuthSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPResponse AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap.AutenticarLDAP(AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequest request) {
            return base.Channel.AutenticarLDAP(request);
        }
        
        public AFEX.plantilla.api.ESB_AFEX_LDAP.UsuarioAplicacion[] AutenticarLDAP(string usuario, string password, AFEX.plantilla.api.ESB_AFEX_LDAP.AplicacionAuth aplicacion) {
            AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequest inValue = new AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequest();
            inValue.Body = new AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.aplicacion = aplicacion;
            AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPResponse retVal = ((AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap)(this)).AutenticarLDAP(inValue);
            return retVal.Body.AutenticarLDAPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPResponse> AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap.AutenticarLDAPAsync(AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequest request) {
            return base.Channel.AutenticarLDAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPResponse> AutenticarLDAPAsync(string usuario, string password, AFEX.plantilla.api.ESB_AFEX_LDAP.AplicacionAuth aplicacion) {
            AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequest inValue = new AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequest();
            inValue.Body = new AFEX.plantilla.api.ESB_AFEX_LDAP.AutenticarLDAPRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.aplicacion = aplicacion;
            return ((AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap)(this)).AutenticarLDAPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaResponse AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap.ValidarFirma(AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequest request) {
            return base.Channel.ValidarFirma(request);
        }
        
        public AFEX.plantilla.api.ESB_AFEX_LDAP.ValidacionAuth ValidarFirma(string usuario, string firma) {
            AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequest inValue = new AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequest();
            inValue.Body = new AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.firma = firma;
            AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaResponse retVal = ((AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap)(this)).ValidarFirma(inValue);
            return retVal.Body.ValidarFirmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaResponse> AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap.ValidarFirmaAsync(AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequest request) {
            return base.Channel.ValidarFirmaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaResponse> ValidarFirmaAsync(string usuario, string firma) {
            AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequest inValue = new AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequest();
            inValue.Body = new AFEX.plantilla.api.ESB_AFEX_LDAP.ValidarFirmaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.firma = firma;
            return ((AFEX.plantilla.api.ESB_AFEX_LDAP.IESB_AV_ServicioAuthSoap)(this)).ValidarFirmaAsync(inValue);
        }
    }
}
